### ISSUE TITLE
Rotation glitch

### ISSUE THREAD

**Issue by nicofilliol** [nicofilliol/robotcraft_maze#5]
Sometimes, the robot still turns the wrong direction when solving the pro maze. Probably same condition other way around? Or other special cases?

**Comment by guilyx** [comment]
Argh let me pull and see

**Comment by guilyx** [comment]
![Screenshot 2019-08-23 20:29:44](https://user-images.githubusercontent.com/43545812/63618770-cc298800-c5e4-11e9-80a9-27e248aade22.png)

**Comment by guilyx** [comment]
Test it again and close if it goes through without any weird turns.
